AllCops:
  Exclude:
    - 'Rakefile'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'bin/bundle'


  NewCops: enable

  TargetRubyVersion: 3.1.4

  UseCache: false

Layout/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Documentation:
  Enabled: false
