version: "3.8"
services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
  app:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - rubygems:/usr/local/bundle
    environment:
      RAILS_ENV: development
  rabbitmq:
    image: rabbitmq:3.13.0-alpine
    depends_on:
      - app
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  postgres_data:
  rubygems:
