services:
  db:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    build: .
    hostname: policy-base
    depends_on:
      - db
      - rabbitmq
    ports:
      - 4000:4000
    volumes:
      - .:/opt/app
      - rubygems:/usr/local/bundle
    environment:
      RAILS_ENV: development
      PORT: 4000
  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  postgres_data:
  rubygems:
