default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'postgres') %>
development:
  <<: *default
  database: policy_base_development
test:
  <<: *default
  database: policy_base_test

production:
  <<: *default
  database: policy_base_production
  username: policy_base
  password: <%= ENV['POLICY_BASE_DATABASE_PASSWORD'] %>
